let id = 0
radio.setGroup(1)
radio.setTransmitPower(1)
id = id
basic.showNumber(0)
basic.pause(2000)
basic.clearScreen()
basic.forever(function () {
    basic.showString("a")
    radio.sendNumber(3)
    basic.showString("m")
    radio.sendNumber(3)
    basic.showString("u")
    radio.sendNumber(3)
    basic.showString("s")
    radio.sendNumber(3)
    basic.showString("e")
    radio.sendNumber(3)
    basic.showString("z")
    radio.sendNumber(3)
})
