let id = 0
radio.setGroup(1)
radio.setTransmitPower(1)
id = id
basic.showNumber(0)
basic.pause(2000)
basic.clearScreen()
basic.forever(function () {
    basic.showString("v")
    radio.sendNumber(2)
    basic.showString("a")
    radio.sendNumber(2)
    basic.showString("c")
    radio.sendNumber(2)
    basic.showString("a")
    radio.sendNumber(2)
    basic.showString("n")
    radio.sendNumber(2)
    basic.showString("c")
    radio.sendNumber(2)
    basic.showString("e")
    radio.sendNumber(2)
    basic.showString("s")
    radio.sendNumber(2)
})
