let id = 0
radio.setGroup(1)
radio.setTransmitPower(1)
id = id
basic.showNumber(0)
basic.pause(2000)
basic.clearScreen()
basic.forever(function () {
    basic.showString("B")
    radio.sendNumber(2)
    basic.showString("O")
    radio.sendNumber(2)
    basic.showString("N")
    radio.sendNumber(2)
    basic.clearScreen()
    basic.pause(100)
    basic.showString("N")
    radio.sendNumber(2)
    basic.showString("E")
    radio.sendNumber(2)
    basic.showString("S")
    radio.sendNumber(2)
})
